import './globals.scss';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ChakraProvider, StoreProvider } from '~lib';
import { Layout } from '~ui';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ChakraProvider>
            <Layout>{children}</Layout>
          </ChakraProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
