import './globals.scss';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Chakra, StoreProvider } from '~lib';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <StoreProvider>
          <Chakra>{children}</Chakra>
        </StoreProvider>
      </body>
    </html>
  );
}
